=== thongteav/XMLreader/students.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <xsd:annotation>
      <xsd:documentation xml:lang="en">
         students.xsd XML Schema for defining a bunch of students
      </xsd:documentation>
   </xsd:annotation>  

   <xsd:element name="students">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element name="description" type="xsd:string"
               minOccurs="0" maxOccurs="1"/>
            <xsd:element name="student" type="StudentType"
               minOccurs="0" maxOccurs="unbounded"/>
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>

   <xsd:complexType name="StudentType">
      <xsd:sequence>
         <xsd:element name="firstname" type="xsd:string"
               minOccurs="1" maxOccurs="1"/>
         <xsd:element name="lastname" type="xsd:string"
               minOccurs="1" maxOccurs="1"/>
          <xsd:element name="pictureURL" type="xsd:string"
               minOccurs="0" maxOccurs="1"/>      
                    
         <xsd:element name="birthday" minOccurs="1" maxOccurs="1">
            <xsd:complexType>
               <xsd:attribute name="day" type="xsd:string"
                  use="required"/>
               <xsd:attribute name="month" type="xsd:string"
                  use="required"/>
               <xsd:attribute name="year" type="xsd:string"
                  use="required"/>
            </xsd:complexType>
         </xsd:element>

          <xsd:element name="paper" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>

      </xsd:sequence>
      
      <xsd:attribute name="studentID" type="xsd:string" use="required"/>
      
      <xsd:attribute name="gender" use="optional" default="M">
        <xsd:simpleType>
           <xsd:restriction base="xsd:string">
              <xsd:enumeration value="M"/>
              <xsd:enumeration value="F"/>
           </xsd:restriction>
        </xsd:simpleType>
      </xsd:attribute>
   </xsd:complexType>
</xsd:schema>

=== thongteav/XMLreader/studentdata - Copy.xml
<?xml version="1.0" encoding="ISO-8859-1"?><students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="students.xsd">
    <description>2017 S2 Student Set</description>
    <student gender="F" studentID="9394945">
        <firstname>Queen</firstname>
        <lastname>Elizabeth</lastname>
        <pictureURL>H:\DSA_2016\Assignment3_2017\pics\Queen.jpg</pictureURL>
        <birthday day="03" month="06" year="1980"/>
        <paper>Tea Drinking</paper>
        <paper>Etiquette 101</paper>
    </student>
    <student gender="M" studentID="0122080">
        <firstname>Seth</firstname>
        <lastname>Hall</lastname>
        <pictureURL>H:\DSA_2016\Assignment3_2017\pics\seth_hall.jpg</pictureURL>
        <birthday day="01" month="05" year="1983"/>
        <paper>Highly Secure Systems</paper>
        <paper>Data Structures and Algorithms</paper>
        <paper>Programming 2</paper>
    </student>
    <student gender="M" studentID="1311607">
        <firstname>Adam</firstname>
        <lastname>Campbell</lastname>
        <pictureURL>H:\DSA_2016\Assignment3_2017\pics\Adam.jpg</pictureURL>
        <birthday day="31" month="05" year="1992"/>
        <paper>Neuroinformatic</paper>
        <paper>System Security</paper>
        <paper>Research Methods</paper>
        <paper>Data Mining</paper>
    </student>
    <student gender="F" studentID="12345556">
        <firstname>Hello</firstname>
        <lastname>World</lastname>
        <pictureURL>C:\Users\Thong\Google Drive\2017 Semester 1\Data Structures and Algorithms\Assignment\Assignment 3\StudentXML\robin.png</pictureURL>
        <birthday day="07" month="09" year="1991"/>
        <paper>Flower Art</paper>
        <paper>Sing a song</paper>
    </student>
    <student gender="M" studentID="11994823">
        <firstname>Richard</firstname>
        <lastname>Harrow</lastname>
        <pictureURL>C:\Users\Thong\Google Drive\2017 Semester 1\Data Structures and Algorithms\Assignment\Assignment 3\StudentXML\fernbird.png</pictureURL>
        <birthday day="03" month="01" year="1980"/>
        <paper>Bootlegging</paper>
        <paper>Shooting</paper>
    </student>
</students>

=== thongteav/XMLreader/studentdata.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<students 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="students.xsd">
    <description>2017 S2 Student Set</description>
    <student studentID="0122080" gender="M">
        <firstname>Seth</firstname>
        <lastname>Hall</lastname>
        <pictureURL>H:\DSA_2016\Assignment3_2017\pics\seth_hall.jpg</pictureURL>
        <birthday day="01" month="05" year="1983"/>
        <paper>Highly Secure Systems</paper>
        <paper>Data Structures and Algorithms</paper>
        <paper>Programming 2</paper>
    </student>
    <student studentID="1311607" gender="M">
        <firstname>Adam</firstname>
        <lastname>Campbell</lastname>
        <pictureURL>H:\DSA_2016\Assignment3_2017\pics\Adam.jpg</pictureURL>
        <birthday day="31" month="05" year="1992"/>
        <paper>Neuroinformatic</paper>
        <paper>System Security</paper>
        <paper>Research Methods</paper>
        <paper>Data Mining</paper>
    </student>
    <student studentID="9394945" gender="F">
        <firstname>Queen</firstname>
        <lastname>Elizabeth</lastname>
        <pictureURL>H:\DSA_2016\Assignment3_2017\pics\Queen.jpg</pictureURL>
        <birthday day="03" month="06" year="1980"/>
        <paper>Tea Drinking</paper>
        <paper>Etiquette 101</paper>
    </student>
    <student studentID="11994823" gender="M">
        <firstname>Richard</firstname>
        <lastname>Harrow</lastname>
        <pictureURL>H:\DSA_2016\Assignment3_2017\pics\Richard.jpg</pictureURL>
        <birthday day="03" month="01" year="1980"/>
        <paper>Bootlegging</paper>
        <paper>Shooting</paper>
    </student>
</students>
